name: ll_test
description: A new Flutter project.
version: 1.0.0+1

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #  cache online images
  cached_network_image: ^3.1.0
  #  equatable objects
  equatable: ^2.0.3
  #getx
  get: ^4.3.4
  #Dependency injection
  get_it: ^7.2.0
  #internect checker
  internet_connection_checker: ^0.0.1+2
  #loading progress indicator
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  # toast for user
  fluttertoast: ^8.0.8
  #  responsive screen
  flutter_screenutil: ^5.0.0+2
  # error handler
  dartz: ^0.10.0
  #url launch
  url_launcher: ^6.0.13
  # local storage
  shared_preferences: ^2.0.9
  dio: ^4.0.6
dev_dependencies:
  build_runner: ^2.0.4
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^2.1.3+1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#000000"
  image: "assets/images/native_splash_icon.png"
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: cairo
      fonts:
        - asset: fonts/cairo.ttf